version: '3.8'
services:
  ffc-pay-statement-publisher:
    build:
      context: .
      target: production
    image: ffc-pay-statement-publisher
    container_name: ffc-pay-statement-publisher
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-publisher-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
